site_name: Malachite Docs
site_url: https://draconizations.github.io/malachite/
repo_url: https://github.com/Draconizations/malachite
repo_name: Draconizations/malachite

nav:
  - Home:
    - Welcome:  'index.md'
    - About Malachite: 'about.md'

  - Getting Started:
    - Installation: 'start/installation.md'
  
  - General Concepts:
    - Markup: 'general/markup.md'
    - Frames: 'general/frames.md'
    - Directives: 'general/directives.md'
    - State: 'general/state.md'
    - Lifecycle: 'general/lifecycle.md'
  
  - Directives:
    - x-passage:  'alpine/x-passage.md'
    - x-frame: 'alpine/x-frame.md'
    - x-link: 'alpine/x-link.md'
    - x-fade: 'alpine/x-fade.md'
    - x-reveal: 'alpine/x-reveal.md'
    - $s magic: 'alpine/store.md'

  - API:
    - Alpine: 'api/alpine.md'
    - Config: 'api/config.md'
    - Engine: 'api/engine.md'
    - Frames: 'api/frame.md'
    - Story: 'api/story.md'
    - State: 'api/state.md'


theme:
  name: material
  language: 'en'
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.instant
  palette: 
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: material/diamond

extra:
  version:
    provider: mike
    default: latest
    alias: true

validation:
  anchors: warn

markdown_extensions:
  - admonition
  - sane_lists
  - toc:
      permalink: true
  - footnotes
  - codehilite:
      guess_lang: false
  - attr_list
  - md_in_html
  - extra
  - pymdownx.blocks.caption
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets
  