name: CI
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
    branches:
      - 'main'
    types:
      - opened
      - synchronize
      - reopened
  push:
    paths:
      - 'src/**'
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies # (assuming your project has dependencies)
        run: bun install # You can use npm/yarn/pnpm instead if you prefer
      - name: Run tests
        run: bun test
  # lint:
  #   name: Run Biome CI
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Setup Biome
  #       uses: biomejs/setup-biome@v2
  #       with:
  #         version: latest
  #     - name: Run Biome
  #       run: biome ci .
  build:
    name: Build & Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build format.js
        run: bun run build ./dist
      - name: Typescript types
        run: bun run types
      - name: Commit build
        run: |
          git config user.name 'malachite[bot]'
          git config user.email 'malachite[bot]@users.noreply.github.io'
          git add ./dist
          git commit -m "[bot] update dist"
          git push