name: Tests
on:
  pull_request:
    paths:
      - '.github/**'
      - 'src/**'
      - 'build.ts'
      - 'package.json'
      - 'story.json'
      - 'tests/**'
    branches:
      - 'main'
    types:
      - opened
      - synchronize
      - reopened
  push:
    paths:
      - '.github/**'
      - 'src/**'
      - 'build.ts'
      - 'package.json'
      - 'story.json'
      - 'tests/**'
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test